name: Build and Deploy Whitepaper via ArgoCD

on:
  push:
    branches: ["master", "main", "staging", "stg", "develop", "dev", "**"]
    paths:
      - "**"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target k8s environment
        required: false
        options:
          - dev
          - stg
          - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: gear-foundation/argocd-workflow/.github/workflows/build-and-deploy-via-argocd.yaml@main
    with:
      environment: ${{ inputs.environment }}
      app_name: whitepaper
      component_name: app
      dockerfile_path: ./Dockerfile
      docker_context: ./
    secrets:
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_USER: ${{ secrets.ARGOCD_USER }}
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      ARGOCD_PAT: ${{ secrets.ARGOCD_PAT }}
      TELEGRAM_DEVOPS_CHAT: ${{ secrets.TELEGRAM_DEVOPS_CHAT }}
      TELEGRAM_DEVOPS_TOKEN: ${{ secrets.TELEGRAM_DEVOPS_TOKEN }}
